### ISSUE TITLE
com.onenet.datapush.receiver.Util类中的toString()方法英文逗号写成了中文逗号

### ISSUE THREAD

**Issue by chengwengao** [cm-heclouds/data-push#1]
![image](https://user-images.githubusercontent.com/25266894/39126866-17532018-4736-11e8-87d0-25eee2d45072.png)
com.onenet.datapush.receiver.Util类中的toString()方法英文逗号写成了中文逗号

**Comment by philoyang** [comment]
已修正，谢谢
